#-------------------------------
# General Site Settings

title: Mike Chu's Story | Thank you for visiting.
description: These story for everything such as Life, develop and daily. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mike7chu.github.io" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name: Mike Chu
author-avatar: mike.chu.jpg
email: cnjh0305@kakao.com

#-------------------------------
# Contact links
#facebook:  https://facebook.com/ # Add your Facebook handle
#twitter:   https://twitter.com/ # Add your Facebook handle
instagram: https://www.instagram.com/mike7chu # Add your Facebook handle
#pinterest: https://www.pinterest.com/ # Add your Facebook handle
github: https://github.com/mike7chu
linkedin: https://www.linkedin.com/in/mike-chu-330496b8/?msgOverlay=true

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: Mike # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false# To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: 
  ua: 'UA-72007721-1' # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
